"""Explicit, provenance-bounded system vocabulary assets for Human Manual R1."""
from __future__ import annotations

import hashlib

SYSTEM_VOCABULARY_VERSION = "system-vocabulary-v1"


def _asset(asset_id: str, system: str, text: str, *, identity_synthesis_eligible: bool = True) -> dict:
    return {
        "id": asset_id,
        "inventory_version": SYSTEM_VOCABULARY_VERSION,
        "text": text,
        "grammar_role": "System-specific vocabulary",
        "category": "system_vocabulary",
        "mode_eligibility": ["research"],
        "claim_type_eligibility": ["descriptive"],
        "register": "research",
        "metaphor_family": None,
        "semantic_family": f"system_vocabulary:{system}:{asset_id}",
        "cadence": "single_sentence",
        "reading_level": "plain",
        "epistemic_safety_tags": ["interpretive_only", "no_prediction", "no_diagnosis", "no_empirical_upgrade"],
        "system_eligibility": [system],
        "identity_synthesis_eligible": identity_synthesis_eligible,
        "author": "Inversion Labs",
        "review_status": "accepted",
        "rejection_reason": None,
    }
SYSTEM_VOCABULARY_ASSETS = (
    _asset("sys-astrology-001", "astrology", "In astrology, a sign names the zodiacal sector assigned to a returned chart position; its symbolic interpretation remains separate from the calculation."),
    _asset("sys-astrology-002", "astrology", "An astrological house locates a chart factor within a twelve-part spatial framework and should not be treated as a measured personality trait."),
    _asset("sys-astrology-003", "astrology", "An aspect records an angular relationship between chart points before any traditional meaning is applied."),
    _asset("sys-astrology-004", "astrology", "Retrograde status describes apparent geocentric motion in the calculation and does not by itself establish a behavioral tendency."),
    _asset("sys-astrology-005", "astrology", "The ascendant is sensitive to supplied time and place, so uncertain birth time limits how confidently that calculation can be returned."),
    _asset("sys-astrology-006", "astrology", "Element and modality summaries are derived groupings inside the astrological lens, not independent empirical evidence about a person."),
    _asset("sys-astrology-007", "astrology", "A planet label identifies a calculated chart factor; any psychological language attached to it belongs to the interpretive layer."),
    _asset("sys-astrology-008", "astrology", "Chart geometry can be reproduced from the same inputs even when two astrologers disagree about its meaning."),
    _asset("sys-astrology-009", "astrology", "Repeated astrological symbols may enrich a traditional reading without becoming corroboration from an unrelated evidence system."),
    _asset("sys-astrology-010", "astrology", "Traditional rulership language belongs to astrology's own vocabulary and should stay visibly labeled as tradition rather than measurement."),
    _asset("sys-pythagorean-001", "pythagorean", "The Pythagorean module derives name numbers from its configured letter-value mapping before any symbolic meaning is attached."),
    _asset("sys-pythagorean-002", "pythagorean", "An expression number is a deterministic result of the supplied spelling within this mapping, not a measured ability score."),
    _asset("sys-pythagorean-003", "pythagorean", "A soul-urge calculation uses a defined subset of letters, while the reflective interpretation remains a separate project layer."),
    _asset("sys-pythagorean-004", "pythagorean", "A personality-number calculation uses its configured letter subset and does not establish how other people actually perceive someone."),
    _asset("sys-pythagorean-005", "pythagorean", "Digit reduction is arithmetic within the module; preserving or reducing special values is a declared rule, not hidden intuition."),
    _asset("sys-pythagorean-006", "pythagorean", "Changing the supplied spelling changes the numerical input and can legitimately change the returned Pythagorean result."),
    _asset("sys-pythagorean-007", "pythagorean", "Several Pythagorean calculations derived from one name remain dependent on that same source rather than becoming independent evidence."),
    _asset("sys-pythagorean-008", "pythagorean", "Traditional number meanings are interpretive vocabulary layered onto arithmetic and should never be presented as scientific personality measurement."),
    _asset("sys-pythagorean-009", "pythagorean", "A numerical recurrence can be noted inside the Pythagorean lens without being promoted into a factual claim about identity."),
    _asset("sys-pythagorean-010", "pythagorean", "A match between Pythagorean numerology and another symbolic system is comparison, not automatic cross-validation."),
    _asset("sys-chaldean-001", "chaldean", "The Chaldean module uses its declared letter-value table to calculate a name result before any interpretive language is introduced."),
    _asset("sys-chaldean-002", "chaldean", "A Chaldean name total is deterministic for the supplied spelling and mapping, not an observation of temperament."),
    _asset("sys-chaldean-003", "chaldean", "Reduction rules belong to the calculation contract and should be inspectable separately from traditional number meanings."),
    _asset("sys-chaldean-004", "chaldean", "Different transliterations or spellings can change the Chaldean input, so provenance of the entered name matters."),
    _asset("sys-chaldean-005", "chaldean", "Multiple Chaldean outputs derived from the same name share a dependence source and must not be counted as independent corroboration."),
    _asset("sys-chaldean-006", "chaldean", "A traditional Chaldean interpretation is a lens applied after arithmetic rather than a property discovered by the arithmetic itself."),
    _asset("sys-chaldean-007", "chaldean", "The module can reproduce the same number from the same input while leaving the human free to reject the associated interpretation."),
    _asset("sys-chaldean-008", "chaldean", "Numerical similarity across Chaldean and other mappings may reflect shared input structure instead of separate evidence."),
    _asset("sys-chaldean-009", "chaldean", "The Human Manual keeps Chaldean terminology attached to its own provenance rather than blending it into generic number mysticism."),
    _asset("sys-chaldean-010", "chaldean", "A Chaldean result can support a reflection question without being converted into prediction, status scoring, or clinical conclusion."),
    _asset("sys-gematria-001", "gematria", "The gematria module converts supplied text through its configured value scheme and records the resulting total as a calculation."),
    _asset("sys-gematria-002", "gematria", "A gematria total depends on the exact text and mapping used, so both belong in the provenance of the result."),
    _asset("sys-gematria-003", "gematria", "A reduced gematria value is an arithmetic transformation of the original total rather than an independent observation."),
    _asset("sys-gematria-004", "gematria", "Two phrases sharing a numerical value may be compared symbolically without implying that the number proves a hidden relationship."),
    _asset("sys-gematria-005", "gematria", "Gematria correspondence belongs to a textual-number lens and should not be silently translated into psychological fact."),
    _asset("sys-gematria-006", "gematria", "Transliteration choices can alter a gematria calculation, so the engine should preserve which textual form was actually evaluated."),
    _asset("sys-gematria-007", "gematria", "Repeated values within one text-derived family remain dependent on the same source material rather than independent evidence."),
    _asset("sys-gematria-008", "gematria", "Traditional or modern symbolic commentary should remain visibly distinct from the deterministic sum that precedes it."),
    _asset("sys-gematria-009", "gematria", "A gematria match can invite inspection of language and association without making a claim about destiny or causation."),
    _asset("sys-gematria-010", "gematria", "The Human Manual reports gematria as one inspectable coordinate system among others, not as an authority over the person."),
    _asset("sys-isopsephy-001", "isopsephy", "The isopsephy module calculates text through its configured letter-value scheme and keeps that arithmetic separate from interpretation."),
    _asset("sys-isopsephy-002", "isopsephy", "An isopsephy total is reproducible from the same textual input and mapping but does not measure a personal trait."),
    _asset("sys-isopsephy-003", "isopsephy", "A reduced isopsephy value remains mathematically dependent on the unreduced total rather than becoming new evidence."),
    _asset("sys-isopsephy-004", "isopsephy", "Transliteration and orthographic choices can affect the calculation, so the evaluated text must remain part of its provenance."),
    _asset("sys-isopsephy-005", "isopsephy", "Equal numerical totals can support symbolic comparison without establishing that two names or phrases share an objective essence."),
    _asset("sys-isopsephy-006", "isopsephy", "Historical terminology and modern project usage should remain distinguishable whenever isopsephy is presented to a reader."),
    _asset("sys-isopsephy-007", "isopsephy", "Several values derived from the same name belong to one dependence family even when they are displayed in separate modules."),
    _asset("sys-isopsephy-008", "isopsephy", "Interpretive language attached to an isopsephy result is a reading layer, not a consequence forced by the arithmetic."),
    _asset("sys-isopsephy-009", "isopsephy", "A numerical recurrence may be interesting within this lens while remaining insufficient for prediction or clinical conclusion."),
    _asset("sys-isopsephy-010", "isopsephy", "The Human Manual preserves isopsephy as its own textual-number system instead of treating every numerical mapping as interchangeable."),
    _asset("sys-ordinal-001", "ordinal", "The ordinal module maps letters through ordered alphabet positions and records the resulting total as a deterministic text calculation."),
    _asset("sys-ordinal-002", "ordinal", "An ordinal total changes when the supplied spelling changes because the calculation is bound to the exact text."),
    _asset("sys-ordinal-003", "ordinal", "Ordinal reduction is derived from the same source total and should not be counted as independent corroborating evidence."),
    _asset("sys-ordinal-004", "ordinal", "Alphabet-position arithmetic can be inspected directly without requiring acceptance of any symbolic interpretation."),
    _asset("sys-ordinal-005", "ordinal", "An ordinal number is a property of the selected mapping and input, not a scientific measurement of identity."),
    _asset("sys-ordinal-006", "ordinal", "When ordinal and another numerology method agree, shared letters can explain part of the recurrence without invoking hidden causation."),
    _asset("sys-ordinal-007", "ordinal", "Interpretive associations attached to an ordinal result remain optional reflection prompts rather than factual conclusions."),
    _asset("sys-ordinal-008", "ordinal", "The Human Manual keeps ordinal provenance visible so its output cannot silently merge with Pythagorean or Chaldean calculations."),
    _asset("sys-ordinal-009", "ordinal", "A repeated ordinal pattern can guide a question while leaving the human free to find it irrelevant."),
    _asset("sys-ordinal-010", "ordinal", "Ordinal calculations contribute one textual coordinate and must not be inflated into multiple independent claims from the same name."),
    _asset("sys-chinese-001", "chinese", "The Chinese module can return an I Ching hexagram index as a deterministic mapping while keeping traditional commentary in a separate interpretive layer."),
    _asset("sys-chinese-002", "chinese", "A trigram label belongs to the Chinese symbolic framework and should not be translated into a measured personality category."),
    _asset("sys-chinese-003", "chinese", "A Wu Xing element returned by the module is a system-specific classification whose meaning remains within that tradition's vocabulary."),
    _asset("sys-chinese-004", "chinese", "Hexagram numbering identifies a traditional symbolic structure; the index itself does not predict an event or outcome."),
    _asset("sys-chinese-005", "chinese", "Traditional I Ching interpretation can frame a reflection question without being presented as an empirically validated forecast."),
    _asset("sys-chinese-006", "chinese", "If multiple Chinese-derived outputs come from one birth input, they remain dependent on that common source."),
    _asset("sys-chinese-007", "chinese", "The Human Manual should show the calculation rule separately from commentary so a reader can inspect where interpretation begins."),
    _asset("sys-chinese-008", "chinese", "A symbolic correspondence between a trigram and another lens may be compared without collapsing the two systems into one ontology."),
    _asset("sys-chinese-009", "chinese", "Missing or uncertain input should remain visible rather than being filled with a plausible hexagram, trigram, or element."),
    _asset("sys-chinese-010", "chinese", "Chinese symbolic vocabulary stays provenance-bound even when another system uses superficially similar words such as element or cycle."),
    _asset("sys-human-design-001", "human_design", "Human Design type is a classification returned within that framework and should not be presented as scientific personality measurement."),
    _asset("sys-human-design-002", "human_design", "Authority is Human Design vocabulary for a decision-making concept inside the system, not an external assessment of competence."),
    _asset("sys-human-design-003", "human_design", "A profile combines two line values inside Human Design and remains distinct from demographic or clinical profiling."),
    _asset("sys-human-design-004", "human_design", "Gate numbers identify positions within the Human Design framework before any reflective interpretation is attached."),
    _asset("sys-human-design-005", "human_design", "A channel is a framework-specific relationship between gates and does not by itself establish a behavioral fact."),
    _asset("sys-human-design-006", "human_design", "Center definitions belong to Human Design's internal model and should remain visibly labeled as system-specific interpretation."),
    _asset("sys-human_design-007", "human_design", "Birth-time uncertainty can limit Human Design calculations, so unavailable precision should remain unavailable rather than inferred."),
    _asset("sys-human_design-008", "human_design", "Several Human Design outputs produced from one chart share a common dependence source and are not independent corroboration."),
    _asset("sys-human_design-009", "human_design", "Human Design vocabulary may support self-reflection while leaving lived experience and explicit self-report authoritative over the narrative."),
    _asset("sys-human_design-010", "human_design", "Similar language across Human Design and astrology should not erase the distinct calculation rules and provenance of either system."),
    _asset("sys-kabbalah-001", "kabbalah_tree_of_life", "A Tree of Life mapping belongs to a historical-mystical symbolic framework and should remain distinct from deterministic text or birth calculations."),
    _asset("sys-kabbalah-002", "kabbalah_tree_of_life", "A sephirah label is system-specific vocabulary whose reflective use does not make it a measured psychological category."),
    _asset("sys-kabbalah-003", "kabbalah_tree_of_life", "Project mappings onto the Tree of Life must be labeled as modern interpretive construction when they are not historical attestations."),
    _asset("sys-kabbalah-004", "kabbalah_tree_of_life", "A symbolic path or sephirah correspondence can organize reflection without claiming that the framework discovered an objective trait."),
    _asset("sys-kabbalah-005", "kabbalah_tree_of_life", "Historical terminology, traditional interpretation, and project-authored synthesis should remain separately inspectable in this lens."),
    _asset("sys-kabbalah-006", "kabbalah_tree_of_life", "A repeated symbol across Kabbalistic and numerological layers may share source assumptions and should not be counted automatically as independent evidence."),
    _asset("sys-kabbalah-007", "kabbalah_tree_of_life", "The Human Manual should preserve which Tree of Life convention a mapping uses whenever conventions could produce different readings."),
    _asset("sys-kabbalah-008", "kabbalah_tree_of_life", "A sephirah association can become a question for reflection while clinical labeling, status scoring, and destiny claims remain prohibited inference classes."),
    _asset("sys-kabbalah-009", "kabbalah_tree_of_life", "When a Kabbalistic label resembles language from another lens, the systems should stay side by side rather than being merged."),
    _asset("sys-kabbalah-010", "kabbalah_tree_of_life", "The person remains free to reject a Tree of Life interpretation even when its underlying mapping is reproduced deterministically."),
    _asset("sys-linguistic-001", "linguistic", "Letter count is a property of the supplied text and orthography, not a measurement of personality or intelligence."),
    _asset("sys-linguistic-002", "linguistic", "Unique-letter count describes textual variety within the chosen spelling and should not be promoted into a trait claim."),
    _asset("sys-linguistic-003", "linguistic", "Vowel ratio is a deterministic text statistic whose numerical precision does not make a symbolic interpretation scientifically validated."),
    _asset("sys-linguistic-004", "linguistic", "Entropy ratio summarizes distribution in the supplied text and should remain separate from psychological concepts that also use the word entropy."),
    _asset("sys-linguistic-005", "linguistic", "A syllable estimate depends on the estimator and language assumptions, so its limitations belong beside the returned value."),
    _asset("sys-linguistic-006", "linguistic", "Changing spelling, script, punctuation, or transliteration can alter linguistic metrics because the text itself is the measured object."),
    _asset("sys-linguistic-007", "linguistic", "Several linguistic metrics from one name share the same source string and therefore do not become independent evidence about the person."),
    _asset("sys-linguistic-008", "linguistic", "Text-derived measures can describe the submitted representation without claiming that the representation exhausts the human behind it."),
    _asset("sys-linguistic-009", "linguistic", "A linguistic recurrence can support comparison between texts while remaining silent about destiny, motive, clinical conclusions, or worth."),
    _asset("sys-linguistic-010", "linguistic", "The Human Manual keeps textual statistics in an observational layer and labels any later symbolic reading as interpretation."),
    _asset("sys-tarot-001", "tarot", "A Tarot card identifies an optional symbolic archetype for reflection and does not contribute an identity score.", identity_synthesis_eligible=False),
    _asset("sys-tarot-002", "tarot", "Tarot imagery belongs to a separate reflective surface and should not be presented as a deterministic natal calculation.", identity_synthesis_eligible=False),
    _asset("sys-tarot-003", "tarot", "A card meaning can invite a question without predicting an event, diagnosing a condition, or assigning a permanent trait.", identity_synthesis_eligible=False),
    _asset("sys-tarot-004", "tarot", "The selected card and the interpretation applied to it should remain separately inspectable in provenance.", identity_synthesis_eligible=False),
    _asset("sys-tarot-005", "tarot", "Repeated Tarot imagery may feel resonant while remaining symbolic recurrence rather than empirical validation.", identity_synthesis_eligible=False),
    _asset("sys-tarot-006", "tarot", "A Tarot reading should preserve the person's freedom to disagree, reinterpret, or discard the prompt entirely.", identity_synthesis_eligible=False),
    _asset("sys-tarot-007", "tarot", "Card titles are narrative vocabulary rather than factual labels placed on the person being described.", identity_synthesis_eligible=False),
    _asset("sys-tarot-008", "tarot", "Tarot can sit beside other lenses in the atlas without being merged into their calculation rules.", identity_synthesis_eligible=False),
    _asset("sys-tarot-009", "tarot", "A reflective card prompt should stay visibly optional even when it echoes themes found elsewhere in the Manual.", identity_synthesis_eligible=False),
    _asset("sys-tarot-010", "tarot", "The Human Manual keeps Tarot separate from identity analysis so symbolic storytelling cannot masquerade as evidence.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-001", "sumerian_me", "The historical Sumerian me layer treats textual attestations as historical evidence and modern thematic groupings as project-authored analysis.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-002", "sumerian_me", "A named me from a surviving text is not an ancient personality attribute assigned to a modern individual.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-003", "sumerian_me", "Modern categories used to organize me are analytical conveniences and should not be described as an ancient canonical taxonomy.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-004", "sumerian_me", "Historical translation, scholarly interpretation, disputed reconstruction, and project reflection must remain visibly distinct layers.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-005", "sumerian_me", "A damaged or uncertain textual item should remain uncertain rather than being completed into a cleaner modern story.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-006", "sumerian_me", "The count of retained me depends on the stated textual corpus and inclusion rules rather than representing a universal canonical total.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-007", "sumerian_me", "A modern reflection may compare a me theme with lived experience only when that comparison is labeled as modern interpretation.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-008", "sumerian_me", "Historical Sumerian vocabulary should not be blended into astrology, numerology, Tarot, or Human Design as though the systems shared one source.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-009", "sumerian_me", "Primary textual evidence should remain inspectable so a reader can distinguish what the source says from what the project infers.", identity_synthesis_eligible=False),
    _asset("sys-sumerian-me-010", "sumerian_me", "The Sumerian me lens can deepen historical reflection without claiming that an ancient institution secretly defines a modern person.", identity_synthesis_eligible=False),
)


def select_system_vocabulary(system: str | None, seed: str, *, for_identity_synthesis: bool = True) -> dict | None:
    if not system:
        return None
    options = [item for item in SYSTEM_VOCABULARY_ASSETS if system in item["system_eligibility"]]
    if for_identity_synthesis:
        options = [item for item in options if item["identity_synthesis_eligible"]]
    if not options:
        return None
    digest = hashlib.sha256(f"{system}|{seed}|{SYSTEM_VOCABULARY_VERSION}".encode()).digest()
    return options[int.from_bytes(digest[:8], "big") % len(options)]


# R2: explicit authored vocabulary for implemented roadmap/data-source systems.
R2_SYSTEM_TEXTS = {
    "alchemical_transformation": (
        "The alchemical stage is selected by a declared numerical convention; the stage name is symbolic vocabulary rather than a clinical assessment of personal development.",
        "Nigredo, albedo, citrinitas, and rubedo belong to an interpretive historical vocabulary whose use here is a modern reflective correspondence.",
        "A returned alchemical stage can organize a question about change without implying that a person is objectively located on a universal transformation ladder.",
        "The letter total that selects an alchemical index remains dependent on the supplied name even when the resulting stage is displayed as a separate lens.",
        "Alchemical imagery can enrich narrative language while historical practice, modern symbolism, and personal reflection remain separately labeled.",
    ),
    "apollonius": (
        "The Apollonius module returns a versioned symbolic profile derived from its configured textual convention, not an historical claim about the modern subject.",
        "A dominant planet in this module is a project correspondence and should remain distinct from astronomical planetary placement in the natal chart.",
        "The returned primary virtue is reflective vocabulary attached to this module's calculation rather than an independently observed character trait.",
        "A contemplation ratio is a deterministic numerical output whose precision does not upgrade its symbolic interpretation into empirical psychology.",
        "Apollonius-derived values may be inspected beside other lenses, but shared words must not be treated as evidence that the systems have a common origin.",
    ),
    "arabic_abjad": (
        "Arabic Abjad values depend on the declared Abjad ordering and the exact text representation used for the calculation.",
        "A Latin-transliteration proxy is an input convention, not a substitute for claiming that an Arabic-script lexical analysis was performed.",
        "The reduced Abjad value is arithmetically dependent on the unreduced total and therefore does not count as separate evidence.",
        "Abjad correspondences can be used as historical-symbolic number vocabulary while transliteration limits remain visible beside the result.",
        "A numerical echo between Abjad and another name system may reflect shared source text rather than independent confirmation of a personal theme.",
    ),
    "babylonian_planetary": (
        "The Babylonian planetary module uses a declared Chaldean planetary ordering as a symbolic index, not as a reconstruction of an ancient natal chart.",
        "A returned planetary name in this module is selected by the indexing convention and must stay distinct from calculated astronomical positions.",
        "The Chaldean-order index is deterministic for its input total while any personal interpretation of the planet remains optional and symbolic.",
        "Historical planetary-order vocabulary can be preserved without implying that modern personality meanings were present in the ancient source.",
        "When the same name total feeds several symbolic systems, their outputs remain dependent even when their traditional vocabularies differ.",
    ),
    "binary_prime": (
        "Binary-prime metrics are deterministic transforms of the supplied name string and describe the encoding process rather than the person.",
        "A prime-reduced value is mathematically downstream from the same textual input and should not be counted as independent evidence.",
        "Binary weight records the structure of an encoding and carries no intrinsic psychological meaning until a separate interpretive layer is added.",
        "A polarity ratio is a numerical property of the chosen binary representation, not a measured balance of human traits or motives.",
        "Entropy-like values in the binary-prime module refer to encoded data structure and must not be conflated with clinical, cognitive, or thermodynamic claims.",
    ),
    "cuneiform_magic": (
        "The cuneiform module performs structural Unicode-sign analysis only and does not infer a lexical Sumerian or Akkadian reading from modern text.",
        "A cuneiform sign count is meaningful only when cuneiform Unicode characters are actually present in the supplied representation.",
        "The label magic identifies the historical-symbolic module boundary and does not authorize ritual claims, supernatural certainty, or invented translations.",
        "When lexical decoding is marked not attempted, that absence must remain explicit rather than being filled with a plausible ancient-language gloss.",
        "Cuneiform structural evidence can document script presence without being converted into an ancient personal attribute.",
    ),
    "egyptian": (
        "The Egyptian module separates modern transliteration mechanics from decan indexing so that textual and calendrical operations remain inspectable.",
        "A decan index in this implementation is a civil-calendar symbolic index and is explicitly not an astronomical reconstruction.",
        "Uniliteral transliteration is a transformation of supplied text under a declared convention rather than proof of an ancient Egyptian personal name.",
        "A hieroglyphic Unicode count describes the submitted character stream and does not imply that untranslated signs have been linguistically understood.",
        "Egyptian symbolic vocabulary should preserve the difference between attested writing systems, later esoteric associations, and project-authored reflection.",
    ),
    "egyptian_maat": (
        "The Ma'at module's balance value is a formal letter-ratio construction and is not a moral score or judgment of character.",
        "Vowel and consonant counts describe the supplied text representation rather than ethical standing, spiritual status, or psychological equilibrium.",
        "Ma'at is historically rich vocabulary, but this implementation uses a bounded symbolic correspondence rather than claiming an ancient personality test.",
        "A numerical balance can invite reflection on proportion while leaving actual conduct and values to lived evidence and explicit self-report.",
        "The scope statement travels with the Ma'at output so mathematical neatness cannot be mistaken for moral authority.",
    ),
    "elder_futhark": (
        "The Elder Futhark module maps compatible letters through a declared rune order and records unmapped Latin material rather than silently inventing equivalents.",
        "A rune total is deterministic under the configured transliteration convention and does not establish an ancient Germanic identity or destiny.",
        "Unmapped letters are evidence about the limits of the transliteration, not defects that should be repaired with speculative rune assignments.",
        "Runic symbolism can be offered as a separate historical-reflective lens while modern name input remains clearly identified as modern input.",
        "A numerical recurrence between runes and another alphabetic system remains dependent on the same source name unless independent evidence exists.",
    ),
    "esoteric_bridge": (
        "The esoteric bridge records an explicit project crosswalk among systems and must never be mistaken for evidence that the source traditions were historically unified.",
        "A bridge link is comparison metadata, not a new observation and not an additional vote in cross-system convergence.",
        "Tarot, Kabbalah, astrology, and numerology retain separate provenance even when a project-authored correspondence places them on one comparison surface.",
        "Birth-data participation is recorded so a reader can distinguish name-derived links from links that also depend on natal inputs.",
        "The bridge exists to make assumptions inspectable; resemblance across systems remains a hypothesis for comparison rather than empirical validation.",
    ),
    "hermes_thoth_nabu": (
        "The Hermes-Thoth-Nabu module is a comparative lineage lens and explicitly does not claim that the named deities are historically identical.",
        "A comparative correspondence can preserve shared scholarly themes while keeping Egyptian, Greek, and Mesopotamian contexts distinct.",
        "The module's name-derived index is modern project machinery rather than an ancient method for assigning a deity to a person.",
        "Historical comparison should distinguish attested roles and texts from later syncretism and from present-day interpretive synthesis.",
        "This lineage belongs in a provenance-rich comparative layer and is excluded from ordinary identity claims unless a user deliberately explores it.",
    ),
    "hermetic_principles": (
        "The seven-principles scheme used here is modern Hermetic vocabulary and should not be projected backward onto every historical Hermetic text.",
        "A returned principle is selected by a deterministic project convention while its reflective meaning remains interpretive.",
        "The principle index is downstream from the same name-derived total and therefore does not add independent evidentiary support.",
        "Correspondence, vibration, polarity, rhythm, cause and effect, gender, and mentalism remain terms inside this selected modern framework.",
        "A Hermetic principle can frame a reflection question without becoming a law of psychology, physics, or personal destiny.",
    ),
    "indus_valley": (
        "The Indus script remains undeciphered, so this module records structural character information without pretending to recover lexical meaning.",
        "A symbol count describes the supplied representation and cannot establish what an Indus sign meant in its archaeological context.",
        "When lexical reading is unavailable, the backend must preserve that null state instead of manufacturing a translation.",
        "Modern text transformed into an Indus-themed structural lens is not evidence of historical continuity, ancestry, or personal identity.",
        "Indus Valley material is retained for transparent structural comparison and is excluded from ordinary identity narration.",
    ),
    "mandaean_duodecimal": (
        "The Mandaean duodecimal module currently represents a number in base twelve and does not claim to perform a lexical Mandaic reading.",
        "Base-twelve digits are a deterministic representation of the source total rather than a separate observation about the person.",
        "Historical association with a tradition must remain distinct from the mathematical fact that an integer can be expressed in duodecimal notation.",
        "The scope note prevents a numeral-system exercise from being overstated as a complete Mandaean symbolic interpretation.",
        "Duodecimal structure can be compared with other number systems while shared input dependence remains explicit.",
    ),
    "mayan_tzolkin": (
        "The Tzolk'in module uses the declared GMT correlation to compute a calendar position and keeps that convention visible with the result.",
        "A returned day name and number are calendrical coordinates within the selected correlation, not measured personality traits.",
        "Different correlation constants can shift calendar conversion, so the chosen correlation belongs to the provenance of every result.",
        "A Tzolk'in reading may preserve traditional calendar vocabulary while modern personal interpretation remains a separately labeled layer.",
        "Birth-derived calendar coordinates can be reproduced from the same inputs without implying a forecast or fixed life role.",
    ),
    "ogham": (
        "The Ogham module uses a declared medieval letter-tree correspondence and does not present that correspondence as a universal ancient Celtic doctrine.",
        "A tree count is a deterministic result of the selected mapping and supplied text rather than an observation of temperament.",
        "Individual Ogham letters can retain their own historical and manuscript context even when a later tree association is used for reflection.",
        "Unmapped characters and convention limits should remain visible rather than being silently repaired into a cleaner symbolic reading.",
        "Ogham correspondences can enrich the atlas while ancestry, ethnicity, and claims of spiritual status remain outside the inference contract.",
    ),
    "sacred_geometry": (
        "The sacred-geometry module uses integer-indexed constructions such as polygon sides and tetractys layers as symbolic correspondences.",
        "A polygon-side count is selected by a declared arithmetic rule and is not evidence that a person's identity has an objective geometric form.",
        "The tetractys layer is a project correspondence derived from a number, not an archaeological or historical claim about the subject.",
        "Digital-root recurrence remains dependent on its source total even when geometry gives the result a different visual vocabulary.",
        "Geometric language can support visualization and reflection while mathematical structure and symbolic interpretation stay explicitly separated.",
    ),
    "solomonic": (
        "The Solomonic module is indexing-only: it does not invoke entities, prescribe ritual practice, or claim supernatural effects.",
        "A Shem index is a deterministic correspondence under the selected convention and should not be treated as a personal spiritual-status hierarchy.",
        "The returned planet is an index label inside this module and remains distinct from astronomical positions in the natal chart.",
        "Entity names are intentionally excluded from the ordinary result surface unless a separate, explicitly scoped feature requires them.",
        "Solomonic historical and ritual sources require their own provenance; a modern numerical index is not evidence of ancient personal assignment.",
    ),
    "sumerian_me_ontology": (
        "The Sumerian me inventory is historical-textual evidence first; it is not an ancient personality system waiting to be mapped onto modern people.",
        "The nine thematic categories are modern analytical groupings and must never be described as categories asserted by the Sumerian source text.",
        "The retained item count depends on the stated ETCSL recitation and exclusion of damaged placeholders rather than representing a universal canonical total.",
        "Personal mapping is disabled by default because the historical corpus does not establish a rule from modern names or birth data to a particular me.",
        "Primary evidence, scholarly interpretation, disputed reconstruction, and project-authored reflection remain separate epistemic layers throughout the Sumerian module.",
    ),
    "sumerian_sexagesimal": (
        "The sexagesimal module expresses a decimal total in base sixty and does not claim that ancient Mesopotamians used this conversion as a personality method.",
        "Base-sixty digits are mathematically dependent on the original total and therefore do not create a new independent evidence source.",
        "Mesopotamian place-value history can be explained accurately without turning a numeral system into an ancient personal classification.",
        "A sexagesimal representation can support cross-system numerical comparison while historical usage and modern reflection remain separately labeled.",
        "The declared place-value base is part of the computational convention and should travel with any exported sexagesimal result.",
    ),
    "tartaria_architecture": (
        "The architecture module explicitly does not treat Tartaria as an established historical polity or architectural tradition.",
        "Its proportion index is a modern symbolic geometry exercise and must not be presented as evidence for suppressed historical claims.",
        "Polygon-side correspondence belongs to the project's architectural-proportion layer rather than to a verified Tartarian design canon.",
        "Historical-claim status is first-class output so a visually compelling pattern cannot erase the evidentiary boundary.",
        "This module is excluded from ordinary identity narration and remains available only as a bounded example of architectural symbolism and claim hygiene.",
    ),
    "temporal_numerology": (
        "Temporal numerology returns date-derived values such as life path, birthday number, and personal year under a declared Pythagorean convention.",
        "A personal-year value changes with the stated year and should not be mistaken for a prediction of events during that year.",
        "Life-path and birthday numbers share birth-date input and therefore remain dependent calculations rather than independent confirmations.",
        "The as-of year is part of the result provenance because changing it can change the temporal calculation while the birth data stays constant.",
        "Date-derived number symbolism can frame a time-bounded reflection without assigning inevitability, luck, or assured outcomes.",
    ),
    "unicode_codepoint": (
        "The Unicode module measures encoded text properties such as scalar values and UTF-8 length without attaching intrinsic personal meaning.",
        "A codepoint sum is deterministic for the exact normalized string and Unicode representation used by the engine.",
        "UTF-8 byte length describes data encoding, not linguistic complexity, intelligence, spiritual significance, or character.",
        "Unicode script metadata should reflect actual detected characters and remain empty when the submitted text does not establish a script claim.",
        "Codepoint arithmetic can serve as an inspectable computational lens while interpretation remains clearly downstream and optional.",
    ),
    "vedic_jyotish": (
        "The Jyotish module withholds sidereal placement when ephemeris, precise time, timezone, or location requirements are not satisfied.",
        "A nakshatra should be emitted only from a valid sidereal lunar position under a declared ayanamsa rather than inferred from tropical astrology.",
        "Ayanamsa choice is part of the computational convention because different sidereal offsets can change a returned sign or lunar-mansion boundary.",
        "Vimshottari dasha and divisional charts require their own validated calculations and must not be simulated from a partial Jyotish placeholder.",
        "Jyotish terminology remains provenance-bound to its own astronomical and traditional framework rather than being blended into tropical astrology.",
    ),
}

R2_NON_IDENTITY_SYSTEMS = {
    "cuneiform_magic", "hermes_thoth_nabu", "indus_valley",
    "sumerian_me_ontology", "tartaria_architecture",
}

SYSTEM_VOCABULARY_ASSETS += tuple(
    _asset(
        f"sys-{system.replace('_', '-')}-r2-{index:03d}",
        system,
        sentence,
        identity_synthesis_eligible=system not in R2_NON_IDENTITY_SYSTEMS,
    )
    for system, sentences in R2_SYSTEM_TEXTS.items()
    for index, sentence in enumerate(sentences, 1)
)
