"""Original card-specific reflective prompts; no forecast or reversed reading."""
# Rank order: Ace through Ten, Page, Knight, Queen, King.
MINOR = {
"Wands": [
("creative possibility", "give one exciting idea a first experiment", "a living branch held toward open ground"),
("planning beyond the familiar", "compare the comfort of staying with the preparation required to explore", "a figure looking beyond the walls with a world in hand"),
("expansion and patience", "identify what you have set in motion and what now needs time", "ships on the horizon beyond a watchful figure"),
("shared celebration", "recognize the people and conditions that made a milestone possible", "a garland marking a place of welcome"),
("competing approaches", "turn a clash of methods into a clear conversation about the task", "several staffs crossing without a common rhythm"),
("recognition", "receive acknowledgment while remembering the work and help behind it", "a rider returning through a gathered crowd"),
("holding your ground", "choose which boundary matters enough to explain and maintain", "one person keeping a position against several approaching staffs"),
("momentum", "decide what needs attention before speed makes the choice for you", "staffs traveling together through open air"),
("persistence with limits", "ask whether you need another effort, a pause, or some support", "a watchful figure beside a boundary of staffs"),
("accumulated responsibility", "set down or renegotiate one task you have carried by default", "a bundle so large it obscures the road ahead"),
("curious initiative", "explore an interest without demanding immediate expertise", "a young observer studying a sprouting staff"),
("energetic pursuit", "give enthusiasm a direction and a practical stopping point", "a rider in motion across an open landscape"),
("confident participation", "make space for your own contribution while welcoming someone else's", "a seated figure with a flowering symbol and an attentive companion"),
("direction through example", "state a purpose clearly enough that others can choose how to participate", "a leader holding a staff rather than every rein"),
],
"Cups": [
("emotional openness", "notice what you would like to welcome and what makes room for it", "water overflowing a cup into a wider pool"),
("mutual exchange", "ask what each person is offering and what each needs to hear", "two figures meeting with cups held at equal height"),
("companionship", "make time for a shared experience that asks for no performance", "three raised cups forming a small circle"),
("reconsidering an offer", "notice whether a pause reflects discernment, fatigue, or simple lack of interest", "a seated figure with an offered cup at the edge of attention"),
("disappointment and what remains", "name what did not work while noticing support still available", "fallen cups in front of two that remain standing"),
("memory and generosity", "bring forward something kind from the past without requiring its return", "a small cup of flowers passed between figures"),
("many imagined possibilities", "separate a vivid possibility from the evidence needed to choose it", "several cups carrying very different images"),
("leaving what no longer fits", "ask what is unfinished and what you have already learned enough from", "a traveler moving beyond an arrangement of cups"),
("satisfaction", "describe what enough would feel like without making it a permanent state", "a figure seated before a carefully arranged row of cups"),
("shared fulfillment", "notice which everyday actions support the sense of connection you value", "a rainbow of cups above a shared scene"),
("a surprising feeling", "listen to an unexpected response before deciding what it means", "an unlikely visitor emerging from a cup"),
("an invitation", "compare a beautiful intention with the action that would make it credible", "a rider carrying a cup carefully toward an encounter"),
("attentive care", "listen closely while preserving room for your own response", "a figure studying a cup beside the water"),
("emotional steadiness", "hold a feeling and a responsibility together without dismissing either", "a steady seat surrounded by moving water"),
],
"Swords": [
("clarity", "write the distinction that makes a confused situation easier to examine", "a single blade lifted into clear air"),
("a difficult choice", "identify one piece of information that could help you decide", "two crossed blades held in a deliberate pause"),
("painful understanding", "name a difficult feeling without turning it into a story about every future encounter", "a heart and three blades beneath rain"),
("rest and perspective", "create a pause in which no immediate answer is required", "a quiet resting place beneath suspended blades"),
("the cost of winning", "ask whether proving a point would damage something more important", "gathered swords and figures walking away"),
("a gradual transition", "carry forward what is useful while allowing the passage to take time", "a boat moving from troubled water toward a quieter shore"),
("strategy and disclosure", "consider what needs discretion and what needs an honest conversation", "a figure moving carefully with an uneven bundle of swords"),
("perceived restriction", "separate an actual limit from an assumption you could test", "a figure surrounded by blades with space between them"),
("a thought that grows in solitude", "put a troubling thought into words and distinguish observation from anticipation", "a seated figure facing a row of blades in the dark"),
("a stopping point", "recognize what is no longer workable and identify the support needed for a next step", "a difficult scene with light appearing on the horizon"),
("questioning", "ask a precise question without making suspicion the starting answer", "an alert figure holding a blade in changing wind"),
("forceful pursuit of an idea", "check whether urgency is helping you understand or only helping you argue", "a fast rider moving into a strong wind"),
("clear boundaries", "say what you mean with enough care that another person can respond", "an upright blade beside an open hand"),
("reasoned responsibility", "explain a decision in terms someone affected by it can examine", "a straight blade held from a seat of judgment"),
],
"Pentacles": [
("a practical opportunity", "give a promising possibility a budget of time and attention", "a single coin above a garden path"),
("juggling demands", "name what must be balanced and what can be simplified", "two coins moving inside a continuous loop"),
("collaborative craft", "make each person's contribution and standard of work explicit", "people comparing their work beneath an unfinished structure"),
("holding resources tightly", "ask what protection is useful and what it prevents you from trying", "coins held close at several points of the body"),
("need and available support", "identify a practical source of help without treating need as personal failure", "travelers passing a lit window"),
("giving and receiving", "examine the terms of an exchange as carefully as its generosity", "resources distributed beside a small balance"),
("patient assessment", "compare the effort invested with what is actually developing", "a worker pausing beside a growing crop"),
("deliberate practice", "choose one skill you can improve through a specific repeated action", "a bench where each coin receives careful work"),
("cultivated independence", "recognize what you have built and the conditions that sustain it", "a tended garden with room to move within it"),
("continuity and shared foundations", "ask what you want to preserve and how others can participate in its care", "several generations within an established place"),
("practical learning", "turn an interest into a small lesson you can actually complete", "a learner examining a coin in open ground"),
("reliable effort", "make a promise small enough to keep and useful enough to matter", "a patient rider holding a coin above worked land"),
("everyday stewardship", "improve one practical condition that makes participation easier", "a carefully held coin in a living garden"),
("responsible provision", "consider the obligations that come with managing something valuable", "a seated figure surrounded by cultivated abundance"),
],
}
