"""
Webhook / Export System
========================

Exports identity signatures to external systems via:
- Webhook (POST to URL)
- CSV export
- JSON Lines (JSONL) for streaming
- Markdown report

Usage:
    from src.export import export_csv, export_jsonl, export_webhook
    export_csv("output/unified_signatures.json", "output/identities.csv")
"""

import csv
import json
import os
import urllib.request
import urllib.error
from typing import Optional


def export_csv(signatures_path: str, output_path: str) -> str:
    """Export signatures to CSV format."""
    with open(signatures_path) as f:
        data = json.load(f)

    if isinstance(data, list):
        sigs = {s.get("id", s.get("identity", "")): s for s in data}
    else:
        sigs = data

    # Flatten all features
    rows = []
    all_keys = set()
    for name, sig in sigs.items():
        flat = _flatten(sig)
        flat["name"] = name
        rows.append(flat)
        all_keys.update(flat.keys())

    headers = ["name"] + sorted(all_keys - {"name"})

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)

    return output_path


def export_jsonl(signatures_path: str, output_path: str) -> str:
    """Export signatures to JSON Lines format (one JSON object per line)."""
    with open(signatures_path) as f:
        data = json.load(f)

    if isinstance(data, list):
        sigs = data
    else:
        sigs = [{"name": k, **v} for k, v in data.items()]

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        for sig in sigs:
            f.write(json.dumps(sig) + "\n")

    return output_path


def export_webhook(signatures_path: str, webhook_url: str, batch_size: int = 10) -> dict:
    """POST signatures to a webhook endpoint in batches."""
    with open(signatures_path) as f:
        data = json.load(f)

    if isinstance(data, list):
        sigs = data
    else:
        sigs = [{"name": k, **v} for k, v in data.items()]

    results = {"sent": 0, "failed": 0, "errors": []}

    for i in range(0, len(sigs), batch_size):
        batch = sigs[i:i + batch_size]
        payload = json.dumps({"batch": batch, "count": len(batch)}).encode()

        req = urllib.request.Request(
            webhook_url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                if resp.status < 300:
                    results["sent"] += len(batch)
                else:
                    results["failed"] += len(batch)
                    results["errors"].append(f"HTTP {resp.status}")
        except urllib.error.URLError as e:
            results["failed"] += len(batch)
            results["errors"].append(str(e))
        except Exception as e:
            results["failed"] += len(batch)
            results["errors"].append(str(e))

    return results


def export_markdown_report(signatures_path: str, output_path: str) -> str:
    """Generate a comprehensive markdown report."""
    with open(signatures_path) as f:
        data = json.load(f)

    if isinstance(data, list):
        sigs = {s.get("id", s.get("identity", "")): s for s in data}
    else:
        sigs = data

    lines = [
        "# Identity Signatures Report",
        f"\n**Generated:** {len(sigs)} identities",
        "",
    ]

    # Summary table
    lines.append("| Name | Expression | Soul | Personality | Resonance |")
    lines.append("|------|-----------|------|-------------|-----------|")

    for name, sig in sorted(sigs.items()):
        enc = sig.get("encoders", {})
        pyth = enc.get("pythagorean", {})
        res = sig.get("resonance", {})
        expr = pyth.get("expression", pyth.get("life_path", "?"))
        soul = pyth.get("soul_urge", "?")
        pers = pyth.get("personality", "?")
        score = res.get("score", "?") if isinstance(res, dict) else "?"
        lines.append(f"| {name} | {expr} | {soul} | {pers} | {score} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by Human Metadata Engine v0.4.0*")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return output_path


def _flatten(sig: dict) -> dict:
    vec = {}
    for enc_name, enc_data in sig.get("encoders", {}).items():
        if isinstance(enc_data, dict):
            for k, v in enc_data.items():
                if isinstance(v, (int, float)):
                    vec[f"{enc_name}_{k}"] = float(v)
    return vec
