"""Load the provenance-backed public-figure comparison population.

The catalog is generated by ``tools/sync_famous_people_catalog.py`` from
Wikidata entities with English Wikipedia biographies. It deliberately keeps
birth facts separate from runtime birth encoders: a date without a sourced
birth time is not enough to claim a rising sign or Human Design chart.
"""

from __future__ import annotations

import json
from pathlib import Path


CATALOG_PATH = Path(__file__).resolve().parents[1] / "data" / "famous_people.catalog.json"


def load_famous_reference_catalog(path: Path = CATALOG_PATH) -> dict:
    """Return the checked-in catalog, or an empty valid catalog before sync."""
    if not path.exists():
        return {"schema_version": 1, "records": [], "exclusions": []}
    with path.open(encoding="utf-8") as handle:
        catalog = json.load(handle)
    if not isinstance(catalog, dict) or not isinstance(catalog.get("records"), list):
        raise ValueError(f"Reference catalog at {path} is malformed.")
    return catalog


def famous_reference_identities(path: Path = CATALOG_PATH) -> list[dict]:
    """Return only catalog records safe for name-based comparison.

    Birth information remains in catalog provenance. It is intentionally not
    passed to the engine unless a future source records a verified birth time.
    """
    records = load_famous_reference_catalog(path).get("records", [])
    return [
        {
            "id": record["id"],
            "text": record["text"],
            "reference_qid": record["qid"],
            "reference_source": record["provenance"],
        }
        for record in records
        if record.get("calculation_status") == "core_only"
    ]
